/*
 * enc_gen.c - first half of the encoder cross-check.
 *
 * Writes every encoder in src/enc.h, with randomised operands, as assembly
 * text (argv[1]) next to the word the encoder produced (argv[2]).  The build
 * then assembles the text with the system assembler and tests/enc_check.c
 * compares the two.  Fixed seed: a failure is reproducible.
 */
#include "enc.h"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>

#define SEED 0x243f6a8885a308d3ull
#define CASES 48

static unsigned long long g_s = SEED;
static FILE *g_asm, *g_inc;
static unsigned g_count;

static unsigned rnd(unsigned n)
{
    g_s ^= g_s << 13;
    g_s ^= g_s >> 7;
    g_s ^= g_s << 17;
    return (unsigned)(g_s % n);
}

/* A general-purpose register that is never the stack pointer / zero register. */
static unsigned gpr(void) { return rnd(31); }
static unsigned vreg(void) { return rnd(32); }
/* Signed word offset with `bits` significant bits. */
static int off(unsigned bits) { return (int)rnd(1u << bits) - (int)(1u << (bits - 1)); }

static void emit(uint32_t word, const char *fmt, ...)
{
    char text[128];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(text, sizeof text, fmt, ap);
    va_end(ap);
    fprintf(g_asm, "    %s\n", text);
    fprintf(g_inc, "    {0x%08xu, \"%s\"},\n", word, text);
    g_count++;
}

static const char *const cond[] = {"eq", "ne", "cs", "cc", "mi", "pl", "vs",
                                   "vc", "hi", "ls", "ge", "lt", "gt", "le"};

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: enc_gen cases.S cases.inc\n");
        return 2;
    }
    g_asm = fopen(argv[1], "w");
    g_inc = fopen(argv[2], "w");
    if (!g_asm || !g_inc) {
        perror("enc_gen");
        return 1;
    }
    fprintf(g_asm, "// Generated by tests/enc_gen.c (seed %#llx).\n"
                   "    .section __TEXT,__const\n    .p2align 2\n"
                   "    .globl _enc_ref\n_enc_ref:\n", SEED);

    emit(a64_nop(), "nop");
    emit(a64_ret(), "ret");
    for (int i = 0; i < CASES; i++) {
        unsigned d = gpr(), n = gpr(), m = gpr(), a = gpr(), c = rnd(14);
        unsigned imm12 = rnd(4096), imm16 = rnd(65536), hw = rnd(4), sh = 1 + rnd(63);
        unsigned vd = vreg(), vn = vreg(), vm = vreg();
        emit(a64_movz(d, imm16, hw), "movz x%u, #%u, lsl #%u", d, imm16, hw * 16);
        emit(a64_movk(d, imm16, hw), "movk x%u, #%u, lsl #%u", d, imm16, hw * 16);
        emit(a64_mov(d, m), "mov x%u, x%u", d, m);
        emit(a64_add_imm(d, n, imm12), "add x%u, x%u, #%u", d, n, imm12);
        emit(a64_sub_imm(d, n, imm12), "sub x%u, x%u, #%u", d, n, imm12);
        emit(a64_subs_imm(d, n, imm12), "subs x%u, x%u, #%u", d, n, imm12);
        emit(a64_add(d, n, m), "add x%u, x%u, x%u", d, n, m);
        emit(a64_sub(d, n, m), "sub x%u, x%u, x%u", d, n, m);
        emit(a64_adds(d, n, m), "adds x%u, x%u, x%u", d, n, m);
        emit(a64_subs(d, n, m), "subs x%u, x%u, x%u", d, n, m);
        emit(a64_cmp(n, m), "cmp x%u, x%u", n, m);
        emit(a64_cmp_imm(n, imm12), "cmp x%u, #%u", n, imm12);
        emit(a64_and(d, n, m), "and x%u, x%u, x%u", d, n, m);
        emit(a64_and(d, n, A64_ZR), "and x%u, x%u, xzr", d, n);
        emit(a64_ands(d, n, m), "ands x%u, x%u, x%u", d, n, m);
        emit(a64_orr(d, n, m), "orr x%u, x%u, x%u", d, n, m);
        emit(a64_orr(d, n, A64_ZR), "orr x%u, x%u, xzr", d, n);
        emit(a64_eor(d, n, m), "eor x%u, x%u, x%u", d, n, m);
        emit(a64_eor_lsl(d, n, m, sh), "eor x%u, x%u, x%u, lsl #%u", d, n, m, sh);
        emit(a64_eor_lsr(d, n, m, sh), "eor x%u, x%u, x%u, lsr #%u", d, n, m, sh);
        emit(a64_madd(d, n, m, a), "madd x%u, x%u, x%u, x%u", d, n, m, a);
        emit(a64_mul(d, n, m), "mul x%u, x%u, x%u", d, n, m);
        emit(a64_udiv(d, n, m), "udiv x%u, x%u, x%u", d, n, m);
        emit(a64_csel(d, n, m, c), "csel x%u, x%u, x%u, %s", d, n, m, cond[c]);
        emit(a64_csinc(d, n, m, c), "csinc x%u, x%u, x%u, %s", d, n, m, cond[c]);
        unsigned o8 = 8 * rnd(4096);
        emit(a64_ldr(d, n, o8), "ldr x%u, [x%u, #%u]", d, n, o8);
        emit(a64_str(d, n, o8), "str x%u, [x%u, #%u]", d, n, o8);
        emit(a64_ldrb(d, n, imm12), "ldrb w%u, [x%u, #%u]", d, n, imm12);
        emit(a64_ldr_idx(d, n, m), "ldr x%u, [x%u, x%u]", d, n, m);
        emit(a64_ldr_idx3(d, n, m), "ldr x%u, [x%u, x%u, lsl #3]", d, n, m);
        emit(a64_ldr_d(vd, n, o8), "ldr d%u, [x%u, #%u]", vd, n, o8);
        emit(a64_str_d(vd, n, o8), "str d%u, [x%u, #%u]", vd, n, o8);
        int b26 = off(26), b19 = off(19), b14 = off(14);
        unsigned bit = rnd(64);
        emit(a64_b(b26), "b #%d", b26 * 4);
        emit(a64_bl(b26), "bl #%d", b26 * 4);
        emit(a64_bcond(c, b19), "b.%s #%d", cond[c], b19 * 4);
        emit(a64_cbz(d, b19), "cbz x%u, #%d", d, b19 * 4);
        emit(a64_cbnz(d, b19), "cbnz x%u, #%d", d, b19 * 4);
        emit(a64_tbz(d, bit, b14), "tbz %c%u, #%u, #%d", bit < 32 ? 'w' : 'x', d, bit, b14 * 4);
        emit(a64_tbnz(d, bit, b14), "tbnz %c%u, #%u, #%d", bit < 32 ? 'w' : 'x', d, bit, b14 * 4);
        emit(a64_br(n), "br x%u", n);
        emit(a64_blr(n), "blr x%u", n);
        emit(a64_adr(d, b19), "adr x%u, #%d", d, b19 * 4);
        emit(a64_fadd_d(vd, vn, vm), "fadd d%u, d%u, d%u", vd, vn, vm);
        emit(a64_fmul_d(vd, vn, vm), "fmul d%u, d%u, d%u", vd, vn, vm);
        emit(a64_fdiv_d(vd, vn, vm), "fdiv d%u, d%u, d%u", vd, vn, vm);
        emit(a64_fsqrt_d(vd, vn), "fsqrt d%u, d%u", vd, vn);
        emit(a64_fmov_dd(vd, vn), "fmov d%u, d%u", vd, vn);
        emit(a64_fmov_dx(vd, n), "fmov d%u, x%u", vd, n);
        emit(a64_fmov_xd(d, vn), "fmov x%u, d%u", d, vn);
        emit(a64_fcmp_d(vn, vm), "fcmp d%u, d%u", vn, vm);
        emit(a64_vadd_2d(vd, vn, vm), "add v%u.2d, v%u.2d, v%u.2d", vd, vn, vm);
        emit(a64_veor(vd, vn, vm), "eor v%u.16b, v%u.16b, v%u.16b", vd, vn, vm);
        emit(a64_vmov(vd, vn), "mov v%u.16b, v%u.16b", vd, vn);
        emit(a64_movi_zero(vd), "movi v%u.2d, #0", vd);
    }
    fprintf(g_asm, "    .globl _enc_ref_end\n_enc_ref_end:\n");
    if (fclose(g_asm) != 0 || fclose(g_inc) != 0)
        return 1;
    printf("enc_gen: %u cases\n", g_count);
    return 0;
}
